config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'trombones#index'
  resources :trombones
  get 'users/:screen_name', to: 'users#show', as: :user, constraints: { :screen_name => %r{[^\/]+} }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trombone.rb
class Trombone < ApplicationRecord
  belongs_to :user
  validates :status, presence: true
  validates :status, length: { maximum: 140 }
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :trombones, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
  VALID_SCREEN_NAME = %r{[^\/]+}
  validates :screen_name, format: { with: VALID_SCREEN_NAME }
  validates :name, :screen_name, :email, presence: true
  validates :screen_name, length: { maximum: 13 }
  validates :screen_name, uniqueness: true
  mount_uploader :photo, PhotoUploader

  def to_param
    screen_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Você não tem autorização para realizar essa ação"
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :screen_name, :email, :bio, :photo, :photo_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :screen_name, :email, :bio, :photo, :photo_cache])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/trombones_controller.rb
class TrombonesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_trombone, only: [:edit, :show, :destroy, :edit, :update]

  def index
    skip_authorization
    skip_policy_scope
    @trombone = Trombone.new
    if params[:query].present?
      sql_query = " \
        trombones.status @@ :query \
        OR users.name @@ :query \
        OR users.screen_name @@ :query \
      "
      @trombones = Trombone.joins(:user).where(sql_query, query: "%#{params[:query]}%").order(created_at: :desc)
    else
      @trombones = Trombone.all.order(created_at: :desc)
    end
  end

  def show
  end

  def new
    @trombone = Trombone.new
    authorize @trombone
  end

  def create
    @trombone = current_user.trombones.create(set_params)
    authorize @trombone
    if @trombone.save
      respond_to do |format|
        format.html {redirect_to trombones_path}
        format.js
      end
    else
      respond_to do |format|
        format.html { }
        format.js
      end
    end
  end

  def edit
  end

  def update
    @trombone.update(set_params)
    authorize @trombone
    if @trombone.save
      respond_to do |format|
        format.html {redirect_to trombones_path}
      end
    end
  end

  def destroy
    @trombone.destroy
    redirect_to trombones_path
  end

  private

  def set_trombone
    @trombone = Trombone.find(params[:id])
    authorize @trombone
  end

  def set_params
    params.require(:trombone).permit(:status, :photo, :photo_cache)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find_by_screen_name(params[:screen_name])
    authorize @user
    @trombones = @user.trombones.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_photo(user)
    if user.photo.present?
      (cl_image_path user.photo)
    else
      'https://res.cloudinary.com/dkkvtcelc/image/upload/q_auto:eco/v1537372686/home_page/User-placeholder.png'
    end
  end

  def owner?(trombone)
    user_signed_in? ? trombone.user == current_user : false
  end

  def time(input)
    # input.kind_of?(Time) ? input.getlocal.strftime("%I:%M %p") : input.to_time.getlocal.strftime("%I:%M %p")
    t = input.kind_of?(Time) ? input : input.to_time
    from = Time.now - (Time.now - t)
    time_ago_in_words(from)
  end

  def long_date(date_object)
    I18n.l date_object, format: :long
  end

  def short_date(date_object)
    I18n.l date_object, format: :short
  end

  def search?
    params[:query].present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>No Trombone | Meta a boca no trombone</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-65058907-5"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-65058907-5');
    </script>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/components/navbar' %>
    <%= render 'shared/components/flashes' %>
    <div class="outside-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/components/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/components/_banner_user.html.erb
<div class="banner-user" >
  <div class="banner-content">
    <%= image_tag user_photo(user), class: 'photo-user-banner'  %>
    <h1><%= "@#{user.screen_name}"  %></h1>
    <p><%= user.name  %></p>
    <p><%= "Trombones: #{user.trombones.size} Usuario desde: #{long_date(user.created_at.to_date)}"  %></p>
  </div>
</div>

app/views/shared/components/_card_trombone.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3" id='tromboneId--<%= trombone.id  %>'>
  <div class="card">
    <div class="card-trombone-screen-name"><%= link_to "@#{trombone.user.screen_name.capitalize}", user_path(trombone.user)  %></div>
    <div class="card-content">
      <h2><%= best_in_place_if owner?(trombone) , trombone, :status, as: :textarea, placeholder: 'Clique aqui para editar', ok_button: 'Salvar', cancel_button:'Cancelar'  %></h2>
      <p><%= "Em #{short_date(trombone.created_at.to_date)} há #{time(trombone.created_at.to_time)}"  %></p>
    </div>
    <a href="<%= user_path(trombone.user)  %>">
      <img class="card-user-photo" src='<%= user_photo(trombone.user)  %>'>
    </a>
  </div>
</div>

app/views/shared/components/_container_search_summary.html.erb
<% if search?  %>
  <div class="row search-summary-container">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <h2><%= @trombones.size  %> Resultados com as palavras: <%= params[:query]  %></h2>
    </div>
  </div>
<% end %>

app/views/shared/components/_container_trombones.html.erb
<div class=" row trombrones-container" id='trombones'>
  <%= render 'shared/components/container_search_summary'  %>
  <% trombones.each do |trombone|  %>
    <%= render 'shared/components/card_trombone', trombone: trombone  %>
  <% end %>
</div>

app/views/shared/components/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/components/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/oscarlaf03" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/oscarortizgarcia/"target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Criado por Oscar Ortiz
    <br>
    <a href="mailto:ortizg.oscar@gmail.com">ortizg.oscar@gmail.com</a>
  </div>
</div>

app/views/shared/components/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= render 'shared/forms/form_search' %>
    <%= link_to 'Ver Trombones', trombones_path, class: "navbar-wagon-item navbar-wagon-link"  %>

    <% if user_signed_in? %>
      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag user_photo(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".editar", default: "Editar") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to 'Ver Trombones', trombones_path, class: "navbar-wagon-item navbar-wagon-link"  %>
        </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-cog"></i>  <%= t(".editar", default: "Editar") %>
          <% end %>
        </li>

        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
        <% else %>
          <li>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/forms/_form_search.html.erb
<%= form_tag trombones_path, method: :get, class: 'form-inline search-form' do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Ache um trombonasso"
  %>
  <%= submit_tag 'Bora', class: 'btn btn-sm btn-primary'  %>
<% end %>

app/views/shared/forms/_form_trombone.html.erb
<% if user_signed_in? %>
  <div class="trombone-form-container">
    <%= simple_form_for(trombone, html: {class: 'trombone-form'}, remote: true) do |f|   %>
      <%= f.input :status, label: false, placeholder: 'Fala a real'  %>

      <div class="row">
        <div class="col-xs-6">
          <%= f.submit class: 'btn btn-md btn-primary' %>
        </div>
        <!-- <div class="col-xs-6 align-right ">
          <%= f.input :photo, label: false, hint: 'Adicionar foto'  %>
          <%= f.input :photo_cache, as: :hidden %>
        </div> -->

      </div>
    <% end %>
  </div>
<% end %>

app/views/trombones/create.js.erb
// Here you generate *JavaScript* that would be executed in the browser
function refreshForm(innerHTML) {
  const newTromboneForm = document.getElementById('new_trombone');
  newTromboneForm.innerHTML = innerHTML;
}

function addTrombone(tromboneHTML) {
  const trombones = document.getElementById('trombones');
  trombones.insertAdjacentHTML('afterbegin', tromboneHTML);
}

<% if @trombone.errors.any? %>
  refreshForm('<%= j render "shared/forms/form_trombone", trombone: @trombone %>');
<% else %>
  addTrombone('<%= j render "shared/components/card_trombone", trombone: @trombone %>');
  refreshForm('<%= j render "shared/forms/form_trombone", trombone: Trombone.new %>');
<% end %>

app/views/trombones/edit.html.erb
<div class="container">
  <%= render 'shared/forms/form_trombone', trombone: @trombone %>
</div>

app/views/trombones/index.html.erb
<div class="container">
  <div class="index-trombone-container">
    <%= render 'shared/forms/form_trombone', trombone: @trombone  %>
  </div>

  <%= render 'shared/components/container_trombones', trombones: @trombones  %>
</div>

app/views/trombones/new.html.erb
<div class="container">
  <%= render 'shared/forms/form_trombone', trombone: @trombone %>
</div>

app/views/trombones/show.html.erb
<h1>Trombones#show</h1>
<p>Find me in app/views/trombones/show.html.erb</p>

app/views/users/show.html.erb
<%= render 'shared/components/banner_user', user: @user  %>

<div class="container">
  <%= render 'shared/components/container_trombones', trombones: @trombones  %>
</div>